name: flutter_riverpod_template
description: Cinnamon Agency template for Flutter Riverpod applications

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  ###
  # Dependencies
  ###
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  geolocator: ^12.0.0
  intl: ^0.19.0
  just_audio: ^0.9.38
  location: ^6.0.2
  logger_fork: 1.2.0
  logger_flutter_fork: ^1.3.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  go_router: ^14.1.4
  flutter_dotenv: ^5.0.2

  # Freezed
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0

  # UI
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: 1.1.1
  video_player: ^2.8.6
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Riverpod
  flutter_riverpod: ^2.5.1

  # Hive
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  ###
  # Dev Dependencies
  ###
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2

# Trigger code generation
# flutter packages pub run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/movie_list.json
